import PDFDocument from "pdfkit";

/** Tiny placeholder PDF used only by the "send test payslip email" tool. */
export function samplePdf(): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.fillColor("#0a3d62").font("Helvetica-Bold").fontSize(18).text("SOMVANSHI TECHNOLOGIES", { align: "center" });
    doc.moveDown(0.3).fillColor("#64748b").font("Helvetica").fontSize(11).text("Sample Payslip (test email)", { align: "center" });
    doc.moveDown(2).fillColor("#1e293b").fontSize(10)
      .text("This is a sample attachment generated by the SomHR email test tool.")
      .text("Real payslips are generated from approved payroll runs with full salary details.");
    doc.end();
  });
}
